### ISSUE TITLE
Get telegram.org source code and push into branch "original"

### ISSUE THREAD

**Issue by KexyBiscuit** [Telegram-CN/telegram-cn.github.io#1]

**Comment by Hanxv** [comment]
Dirty source code has been reported as finished.

**Comment by KexyBiscuit** [comment]
No directory structure available in previous code... I'm looking forward to getting something that makes sense.

**Comment by KexyBiscuit** [comment]
Commited. Close #1. https://github.com/Telegram-CN/telegram-cn.github.io/commit/2b6e58f2fde9a5493879a73b28a8f326a548263d
